# Generated by Django 3.2.19 on 2023-06-07 20:34

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('degree_type', models.CharField(max_length=200)),
                ('gpa', models.IntegerField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('city', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(upload_to='')),
                ('nav_img', models.ImageField(upload_to='')),
                ('main_txt', models.TextField()),
                ('about_txt', models.TextField(blank=True)),
                ('nav_txt', models.TextField(blank=True)),
                ('resume_txt', models.TextField(blank=True)),
                ('website_link', models.URLField()),
                ('linkedin_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('behance_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('main_img', models.ImageField(upload_to='')),
                ('secondary_img', models.ImageField(blank=True, upload_to='')),
                ('created_date', models.DateField()),
                ('github_link', models.URLField(blank=True)),
                ('live_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('HACK', 'Hacker'), ('MENTOR', 'Mentor'), ('DEV', 'Developer')], default='DEV', max_length=6)),
                ('category', models.CharField(choices=[('FRAME', 'Frameworks'), ('LANG', 'Programming Languages'), ('DATA', 'Data Analysis/Visualization'), ('TEST', 'Testing'), ('TOOL', 'Tools')], default='LANG', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('quote', models.TextField()),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('profile_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
